installer: the much I hate how udev behaves on new rules

diff --git a/src/installer/install b/src/installer/install
--- a/src/installer/install
+++ b/src/installer/install
@@ -48,7 +48,10 @@ if [[ $RESPONSE =~ ^[yY].* ]]
          then echo "creating input group..."
               groupadd input || exit 1
               echo "adding input group udev rule..."
-              install -m644 98-imod-ubuntu14.rules /lib/udev/rules.d/ || { rm -r /opt/input-modifier; exit 1; }
+              install -m644 98-imod-ubuntu14.rules /lib/udev/rules.d/ || { groupdel input; exit 1; }
+              echo "setting input device permissions..."
+              chmod 660 /dev/input/event* || INSEXTRAFAIL=1
+              chown root:input /dev/input/event* || INSEXTRAFAIL=1
        fi
        echo "creating program directory..." 
        mkdir -p /opt/input-modifier || exit 1
@@ -81,8 +84,8 @@ if [[ $RESPONSE =~ ^[yY].* ]]
        fi
        echo "installation finished!"
        if [ $INSEXTRAFAIL -eq 1 ]
-         then echo "however, you may need to reboot before using input-modifier"
-              echo "because we couldn't reload the udev rules or load the uinput module."
+         then echo "however, you will have to reboot before using input-modifier"
+              echo "because we couldn't do some stuff required for it to work immediately."
        fi
        echo "add yourself to the input group in order to be able to use the program:"
        echo "sudo usermod -a -G input <username>"
